title: Learning Irish
description: >-
  This is a reference site for learning Irish!
baseurl: "/learning-irish"
url: "https://codylewis.github.io/"
google_analytics: G-NSHJHZX3K0

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

minima:
  skin: auto
  show_excerpts: false
  hide_site_feed_link: true

collections:
  articles:
    output: true
    permalink: /:title/