title: Learning Irish
description: >-
  This is meant to be a reference site for learning Irish.
baseurl: "/learning-irish"
url: "https://codylewis.github.io/"
github_username:  codylewis
author: Cody Lewis

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  articles:
    output: true
    permalink: /:title/
